spring:
  application:
    name: pickIt

  jackson:
    time-zone: UTC

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time-zone: UTC
jwt:
  secret: ${JWT_SECRET}
  access-token-expire-ms: 3600000
  refresh-token-expire-ms: 86400000

gcp:
  storage:
    bucket: pickit-chat-files

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  cors:
    allowed-origins: >
      http://127.0.0.1:5500,
      http://localhost:5500,
      https://pick-it.site,
      https://www.pick-it.site,
      http://localhost:5173,
      http://localhost:3000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace